name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          cd ~/whatsapp-bot
          git pull origin main
          npm install
          pm2 restart whatsapp-bot || pm2 start npm --name "whatsapp-bot" -- run web
          
    - name: Notify deployment
      run: |
        echo "✅ Deployment completed successfully!"
        echo "Bot is now running on VPS"

# Setup කරන්න අවශ්‍ය GitHub Secrets:
# - VPS_HOST: Your VPS IP address
# - VPS_USERNAME: SSH username (usually 'root' or 'ubuntu')
# - VPS_SSH_KEY: Private SSH key
# - VPS_PORT: SSH port (default 22)
